### ISSUE TITLE
Show a match as soon as it is found.

### ISSUE THREAD

**Issue by voldyman** [akojo/quickfind#7]
Right now all the files are processed first then displayed, how about starting to display matches as soon as they are found?

**Comment by akojo** [comment]
This would defeat the whole idea of scoring substrings higher and then showing better scoring matches first. My biggest frustration with simple common subsequence matching is that you have to spell out almost full paths to really get the match you're looking for.

Here by substring I mean a string of consecutive characters, and by subsequence any characters (consecutive or not) in the same order.
